name: Anchor Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  anchor-test:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v3

      # Node.js for JS/TS tests
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Cache npm packages
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-

      # Install npm deps
      - run: npm ci

      # Install Rust (for BPF build)
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      # Cache cargo binaries (avm, anchor)
      - name: Cache cargo binaries, registry, and target
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-

      # Solana CLI cache
      - name: Cache Solana CLI
        uses: actions/cache@v3
        with:
          path: ~/.local/share/solana
          key: solana-cli-${{ runner.os }}-stable
          restore-keys: solana-cli-

      - name: Install Solana CLI
        run: |
          # Make sure cached path is in PATH first
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"

          # Install only if not already present
          if ! command -v solana >/dev/null; then
            sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          fi

          # Persist for subsequent steps in this workflow
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

          solana --version

      - name: Cache Anchor CLI
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/anchor
            ~/.cargo/bin/anchor
          key: anchor-cli-${{ runner.os }}-latest
          restore-keys: anchor-cli-

      - name: Install Anchor
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          if ! command -v anchor >/dev/null; then
            cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
            avm install latest
            avm use latest
          fi
          export PATH="$HOME/.local/share/anchor/avm/current:$PATH"
          echo "$HOME/.local/share/anchor/avm/current" >> $GITHUB_PATH
          anchor --version

      # Build program
      - name: Build Program
        run: anchor build

      - name: Generate Solana keypair
        run: |
          mkdir -p ~/.config/solana
          solana-keygen new --no-passphrase -o ~/.config/solana/id.json
          solana config set --keypair ~/.config/solana/id.json

      # Run Anchor tests
      - name: Run Anchor Tests
        run: anchor test
